### ISSUE TITLE
Schema 

### ISSUE THREAD

**Issue by AdamYLiang** [kzed-1/Edibles#1]
**Users**
- [x] Typo on `unique` for first point 
- [x] Supplies could be contained in the body, if you want to ability to search by supplies then consider making a tags table. This can be done as a bonus! 

**Misc**
- [x] `Comments`, `Photos`, `Videos` have repeated bullet points. Make sure the column you are referencing exists in table. 

For videos/photos we will ultimately be using AWS/Active Storage to host our photos so they will not need a `url` column. More about this when we have our one-on-one since this is a late MVP. 

Let me know if you have any questions about these changes!

**Comment by kzed-1** [comment]
Which bullet points were repeated for comments, photos, and videos? I'm confused about how wer would add the videos/photos
