### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by AdamYLiang** [kzed-1/Edibles#2]
- [x] `recipes` should have an array of steps. Making a request for a recipe should also bring up relevant steps data.  We can store it in the array for reference if we ever need to count the steps or anything.

- [x] We don't need steps for multiple recipes at once since you can only view steps if you are looking at the recipe. Our steps slice should only hold the relevant information regarding the current recipe that we are looking at. If you go with this approach, you could leave out the steps array. 

Let me know if you have any questions or if you want to talk about this change.

**Comment by kzed-1** [comment]
The array of steps should have elements that are each a step object? or do i only need the step id?
