### ISSUE TITLE
Frontend/Backend Routes

### ISSUE THREAD

**Issue by AdamYLiang** [kzed-1/Edibles#3]
**Frontend Routes**
- [x] `recipe/recipeId` should be `recipe/:recipeId`. Use the `:` to denote the wildcard since this is looking at a single instance of a recipe. 

**Backend Routes**
- [x] No need for `steps`, `images`, `videos` routes. We will fetch that information with the `recipe` and then use jbuilder to format the data. This is because steps are entirely dependent on the recipe. If this gets unwieldy we can break it up but it should be fine.

- [x] No need for `GET` routes for `comments` since we will pass that up when fetching a project as well. 

- [x] Include a search route. If you want to search based off of optional params to an existing route (ex. index) then that is OK as well. 

Let me know if you have any questions or want to talk about these changes!

**Comment by kzed-1** [comment]
not sure if this is what you meant by a search route, not sure how to it works/how to implement it.
