### ISSUE TITLE
User MVP Review

### ISSUE THREAD

**Issue by AdamYLiang** [kzed-1/Edibles#5]
Great work! Functionality is good, here are some changes:

**CSS**
- [x] `Login/Signup` and search bar should be adjusted slightly to make it match the original app. Use the inspector to see how you should adjust it. 
- [x] Put `Demo Log` above the `Login/Signup` forms to match the links for Google/Facebook. Consider changing the color too to match those buttons. 
- [x] Add a space between `member?` and `Login` in `Already a member?Login>>` for the session form. 
- [x] Errors should be larger and matching original app. 
- [x] Add motto/tagline over home splash image to match original app. 

Let me know if you have any questions!

**Comment by kzed-1** [comment]
Hey Adam, I think I completed, these task.
